### PR TITLE
Bigbird language model and Sentencepiece tokenizer

### PR DESCRIPTION
**Pull request by whr778**
Added BigBird and Google native sentencepiece tokenizer.  HF Tokenizers sentencepiece is not compatible with bigbird.
Pretrained two contextual language models to test code.

### CODE REVIEW

**Comment by whr778** [comment]
@ThilinaRajapakse This allows pretraining and finetuning BigBird contextual language models.

**Comment by whr778** [comment]
Hold on this for a few hours ... I need to push one more bug fix

**Comment by whr778** [comment]
@ThilinaRajapakse 
Bigbird works for pretraining and finetuning
XLMRoberta works for finetuning 
# TODO Add XLMRoberta for sentencepiece parsing I can work on this tomorrow if you want to hold this Merge Request???  Otherwise I will add that code and submit another request tomorrow or the next day.  Let me know.

**Comment by ThilinaRajapakse** [comment]
I merged this since it's ready. You can submit another PR for the rest. Thanks!

**Comment by whr778** [comment]
@ThilinaRajapakse Thanks... I just pushed bug fixes... I just pretrained a xlmroberta model...I will submit another PR

**Comment by whr778** [comment]
All bug fixes are in and I am pretraining xlmroberta.

-Bill

**Pull request merged**
