### PR TITLE
Folder creation fix

### PR DESCRIPTION
**Pull request by flaviussn**
As long as `cache_dir` and `output_dir` can be configured, if the path doesn't exist, should be created. 

`mkdir()` can create a single sub-directory and `makedirs()` creates all the intermediate directories

### CODE REVIEW

**Comment by flaviussn** [comment]
I agree. I would change it for every `makedirs`

**Comment by ThilinaRajapakse** [comment]
Great! Thank you!

**Comment by flaviussn** [comment]
Format and lint should be performed. There are a lot of code style inconsistencies in the master version.

**Comment by ThilinaRajapakse** [comment]
Yeah, I'll do the formatting stuff soon.

**Pull request merged**
