### PR TITLE
refactor loss calculation and fix errors

### PR DESCRIPTION
**Pull request by Zhylkaaa**
fixes errors and refactors code, so it doesn't change code except 1 function call. This ensures api is consistent across train, eval and predict methods. Add will allow to add more without hassle (I am planning to try dice loss for ner and add it)

### CODE REVIEW

**Comment by Zhylkaaa** [comment]
@ThilinaRajapakse I saw you are working on this feature, so can you please review this. I think its more maintainable in longterm

**Comment by ThilinaRajapakse** [comment]
I fixed the minor bugs in the PR, but it's good to move this logic to a separate function as you have. I'll merge this.

**Comment by Zhylkaaa** [comment]
I believe this changes were added to master. So can we close this issue?

**Comment by ThilinaRajapakse** [comment]
Yeah, I am not sure why this wasn't closed automatically.

**Pull request closed without merging**
