### PR TITLE
[FIX]add support for models which model and tokenizer are different

### PR DESCRIPTION
**Pull request by aohan237**
make if happen, if the model use different tokenizer with the model.

it can apply to many other models

### CODE REVIEW

**Comment by ThilinaRajapakse** [comment]
I'm not what this pull requests is for. Can you provide some more information please?

**Comment by aohan237** [comment]
@ThilinaRajapakse  most of the time ,the tokenizer is the same model type with the model.
but when do you need to specify the tokenizer_name for the model?  they are different..
so you need to get the specified tokenizer_class if you pass the tokenizer_name.

for example,https://huggingface.co/clue/albert_chinese_small,  this model has the albert model type but with bert tokenizer, in the old cold ,it cant init the tokenizer, then raise exceptions

**Comment by ThilinaRajapakse** [comment]
Ah yes, I see what you mean. I'll merge this soon.

**Comment by ThilinaRajapakse** [comment]
I'm sorry about the delay with this one. Do you mind resolving the conflict with the latest version? It's a trivial change I could do myself, but I wanted to ask if you wanted to do it first.

Please also use a line length of 119 with the formatter for consistency.

**Comment by aohan237** [comment]
of course. thank you for your repo.
i use the 445d386 as the base.
and i will adjust almost all of the models to support if tokenizer and the model type are note the same

**Comment by ThilinaRajapakse** [comment]
Thank you, that would be great!

**Pull request closed without merging**
