### PR TITLE
Add support for FlauBERT model

### PR DESCRIPTION
**Pull request by adrienrenaud**
Hi,

This pull request aims to add support for FlauBERT model as described in the issue #217.

Thanks

### CODE REVIEW

**Comment by adrienrenaud** [comment]
I added a `flaubert_model.py` and modified `classification_model.py`.
I thought it would be enough, but I get the error:

```python
from simpletransformers.classification import ClassificationModel


model = ClassificationModel(
    'flaubert', "flaubert-base-uncased",
)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/.pyenv/versions/pe_reclamation_transformer/lib/python3.7/site-packages/torch/serialization.py in _check_seekable(f)
    226     try:
--> 227         f.seek(f.tell())
    228         return True

AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
~/Projects/FlauBERT/lib/transformers/src/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    466             try:
--> 467                 state_dict = torch.load(resolved_archive_file, map_location="cpu")
    468             except Exception:

~/.pyenv/versions/pe_reclamation_transformer/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    425             pickle_load_args['encoding'] = 'utf-8'
--> 426         return _load(f, map_location, pickle_module, **pickle_load_args)
    427     finally:

~/.pyenv/versions/pe_reclamation_transformer/lib/python3.7/site-packages/torch/serialization.py in _load(f, map_location, pickle_module, **pickle_load_args)
    587 
--> 588     _check_seekable(f)
    589     f_should_read_directly = _should_read_directly(f)

~/.pyenv/versions/pe_reclamation_transformer/lib/python3.7/site-packages/torch/serialization.py in _check_seekable(f)
    229     except (io.UnsupportedOperation, AttributeError) as e:
--> 230         raise_err_msg(["seek", "tell"], e)
    231 

~/.pyenv/versions/pe_reclamation_transformer/lib/python3.7/site-packages/torch/serialization.py in raise_err_msg(patterns, e)
    222                                 " try to load from it instead.")
--> 223                 raise type(e)(msg)
    224         raise e

AttributeError: 'NoneType' object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
 in 
     18     #num_labels=num_labels,
     19     use_cuda=False,
---> 20     args=model_args,
     21 )

~/Projects/FlauBERT/lib/simpletransformers/simpletransformers/classification/classification_model.py in __init__(self, model_type, model_name, num_labels, weight, args, use_cuda, cuda_device, **kwargs)
    140             )
    141         else:
--> 142             self.model = model_class.from_pretrained(model_name, config=self.config, **kwargs)
    143 
    144         self.results = {}

~/Projects/FlauBERT/lib/transformers/src/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
    468             except Exception:
    469                 raise OSError(
--> 470                     "Unable to load weights from pytorch checkpoint file. "
    471                     "If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. "
    472                 )

OSError: Unable to load weights from pytorch checkpoint file. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 
```

**Comment by adrienrenaud** [comment]
I fixed the above issue by making `FlaubertForSequenceClassification` inherit from `FlaubertModel` instead of `XLMPreTrainedModel`. This works because `FlaubertModel` inherits from `XLMPreTrainedModel`.

**Comment by adrienrenaud** [comment]
Now both `flaubert-base-cased` and `flaubert-base-uncased` score high (0.93 accuracy) on the Flue benchmark (book classification, https://github.com/getalp/Flaubert/tree/master/flue#1-text-classification-cls). This is close to the accuracy obtained using `transformers/examples/run_glue.py` as described in https://github.com/getalp/Flaubert/tree/master/flue#b-finetuning-flaubert-with-hugging-faces-transformers-library.

**Comment by adrienrenaud** [comment]
I think this PR could be me merged.
Thanks

**Comment by adrienrenaud** [comment]
I would also like to add support for multilabel classification with FlauBERT. But I will first wait for the review of this PR.

**Comment by kinoute** [comment]
Nice job. Do `flaubert-small-cased` and `flaubert-large-cased` work as well?

**Comment by ThilinaRajapakse** [comment]
@all-contributors please add @adrienrenaud for code

**Comment by adrienrenaud** [comment]
Thanks a lot for accepting this PR and for adding me to the contributors.

**Comment by adrienrenaud** [comment]
> Nice job. Do `flaubert-small-cased` and `flaubert-large-cased` work as well?

Yes they also do. The large model is scoring high (0.92) on the Flue book classification benchmark. The small model is only scoring 0.85 but it is only partially trained at the moment (see: https://github.com/getalp/Flaubert#1-flaubert-models)

**Pull request merged**
