### PR TITLE
Include BERTweet

### PR DESCRIPTION
**Pull request by manueltonneau**
## What changed

For text classification:
- Add model, config and tokenizer. Associated BERTweet with `RobertaConfig`, following the merged PR on HF. 
- In case `model_name=='vinai/bertweet-base'`, assign the `bertweet_normalization` arg value to the `normalization` parameter of the tokenizer

## How to test

```python
from simpletransformers.classification import ClassificationModel
import pandas as pd
model = ClassificationModel('bertweet','vinai/bertweet-base',normalization=True)
df = pd.read_csv(path_to_csv_with_tweets)
df = df[['text','labels']]
model.train_model(df)
```

## Optional TO-DO:
- Include BERTweet for NER and other downstream tasks

### CODE REVIEW

**Comment by manueltonneau** [comment]
@ThilinaRajapakse let me know when you have a chance to take a look!

**Review by ThilinaRajapakse — COMMENTED** [review]
Thank you for the PR and sorry about the delay! I've had an extremely busy couple of weeks (and next week is looking like more of the same).

The PR looks good, but I have one question. Should `bertweet_normalization` always be done with BERTweet or are there cases where it shouldn't be done even with BERTweet? If it's always done, I'm thinking that we could just handle it without the extra parameter.

**Comment by manueltonneau** [comment]
>Thank you for the PR and sorry about the delay! I've had an extremely busy couple of weeks (and next week is looking like more of the same).

Thanks and no worries :) 

> The PR looks good, but I have one question. Should bertweet_normalization always be done with BERTweet or are there cases where it shouldn't be done even with BERTweet? If it's always done, I'm thinking that we could just handle it without the extra parameter.

Good point. On [their repo](https://github.com/VinAIResearch/BERTweet), they show one example without the normalization parameter (by default False) but assume that the input tweet text has been normalized. If it has not been normalized, the default value should always be `bertweet_normalization = True` indeed, since the pre-training data has been normalized in the same way. Will modify the PR to have `normalization=True` as default and discard the extra parameter.

**Comment by manueltonneau** [comment]
I discarded the extra parameter, set `normalization=True` and included normalization for cases where model_name is `'vinai/bertweet-covid19-base-cased'` or `'vinai/bertweet-covid19-base-uncased'` (same architecture and tokenizer as BERTweet but models pre-trained on COVID-related tweets). Ready to merge on my end @ThilinaRajapakse :)

**Comment by ThilinaRajapakse** [comment]
Awesome, thanks!

**Review by ThilinaRajapakse — APPROVED** [review]

**Pull request merged**
