### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manueltonneau**
Added the different versions of ALBERT in the list of current pre-trained models. Also modified names of DistiBERT and ALBERT to fit their official names.

### CODE REVIEW

**Comment by kinoute** [comment]
Nice to see ALBERT added but unfortunately, I can't use it with  `ClassificationModel`. (with 0.8.2).

```py
# Create a ClassificationModel
model = ClassificationModel('albert', 'albert-xlarge-v1', 2, args={"max_seq_length":256, "num_train_epochs": 2, "evaluate_during_training":True, "output_dir": "outputs_w3_jeu", "cache_dir": "cache_w3_jeu", "save_steps": 50},  use_cuda=False)
```

**Comment by ThilinaRajapakse** [comment]
Make sure your transformers library is up to date as well. Albert is working on my machine for both sentence classification and question answering.

**Comment by kinoute** [comment]
@ThilinaRajapakse both packages are up to date:
```bash
root@36d9e58955b0:/# pip list | grep 'transformers'
simpletransformers               0.8.2
transformers                     2.2.0
```

**Comment by ThilinaRajapakse** [comment]
Try running this.

```
from simpletransformers.classification import ClassificationModel
import pandas as pd
import sklearn

# Train and Evaluation data needs to be in a Pandas Dataframe of two columns. The first column is the text with type str, and the second column in the label with type int.
train_data = [['Example sentence belonging to class 1', 1], ['Example sentence belonging to class 0', 0]]
train_df = pd.DataFrame(train_data, columns=['text', 'labels'])


eval_data = [['Example eval sentence belonging to class 1', 1], ['Example eval sentence belonging to class 0', 0]]
eval_df = pd.DataFrame(eval_data)

# Create a TransformerModel
model = ClassificationModel('albert', 'albert-base-v2', use_cuda=False, args={'reprocess_input_data': True, 'overwrite_output_dir': True, 'evaluate_during_training': True, 'logging_steps': 5})
print(train_df.head())

# Train the model
model.train_model(train_df, eval_df=eval_df)
```

**Comment by kinoute** [comment]
It works. Sorry for the inconvenience!

**Comment by ThilinaRajapakse** [comment]
No worries!

**Comment by ThilinaRajapakse** [comment]
@all-contributors please add @mananeau for doc

**Pull request merged**
