### PR TITLE
Don't create cache_dir when no_cache argument is True

### PR DESCRIPTION
**Pull request by henninglebbaeus**

### CODE REVIEW

**Comment by henninglebbaeus** [comment]
I found that the cache_dir directory is created anyways even if the argument no_cache is set True. This is causing a problem for me as I deploy simpletransformers into an environment with read-only filesystem access such as a Google AI Platform Custom Prediction Routine.

**Comment by ThilinaRajapakse** [comment]
Yeah, this is good, thank you. Do you mind making the same change for the other tasks as well? I can do it myself if you like, but I wanted to ask you first!

**Comment by henninglebbaeus** [comment]
I can do it, no problem. Wasn’t aware of the other tasks though

**Comment by henninglebbaeus** [comment]
Done. Added the changes for the other tasks.

**Pull request merged**
