### PR TITLE
replaced print statements in question_answering_model.py with logging

### PR DESCRIPTION
**Pull request by travis-harper**
Switching to logging will be more useful to users who want to use simpletransformers in console-based applications.

### CODE REVIEW

**Comment by travis-harper** [comment]
Needs additional testing on my part, beyond running tests in the Makefile.

**Comment by ThilinaRajapakse** [comment]
As a tip, one thing to keep an eye out for is the `end` argument in print statements.

**Comment by travis-harper** [comment]
You are right. I noticed the formatting on running loss reporting after I made the PR. I'll clean this up and make sure the output looks good in a notebook before reopening.

**Comment by ThilinaRajapakse** [comment]
Thank you!

**Pull request closed without merging**
