### PR TITLE
Tests, linter, formatter and types

### PR DESCRIPTION
**Pull request by flaviussn**
First of all, I want to say thanks for sharing this wonderful wrapper.  :+1: 

**Proposed changes**:
Create a `Make` file to easily make tests, format, lint the code and check types. This sanity checks should be performed always before a PR in order to ensure code quality.

**Status**:
- [x] Made PR ready for code review
- [x] Added  `Makefile` with tests dependency installation, test code, formatter and types.
- [x] Added `setup.cfg` file with Make configuration
- [x] Added some tests for the functionality
- [x] Files linted using `flake8`
- [x] Files formatted using `black`
- [x] Test test code with `pytest`. 

The following folders were excluded for format, lint and test:
- `simpletransformers/experimental` 
- `simpletransformers/classification/transformer_models`
- `simpletransformers/custom_models`

**What is missing**:
- [ ] Update `README.md`
- [ ] Add more test to coverage at least 80% of the code (71% is achived now)
- [ ] perform `make check-readme` in order to remove a warning
- [ ] perform `make types` and resolve errors

Hope is helpful.  :pray: 

### Test results

```bash
============================================== test session starts ==============================================
platform linux -- Python 3.6.10, pytest-5.1.3, py-1.8.1, pluggy-0.13.1
rootdir: /home/flavius/simpletransformers, inifile: setup.cfg
plugins: cov-2.7.1, localserver-0.5.0
collected 24 items                                                                                              

tests/test_classification.py::test_binary_classification[bert-bert-base-uncased] PASSED                   [  4%]
tests/test_classification.py::test_binary_classification[xlnet-xlnet-base-cased] PASSED                   [  8%]
tests/test_classification.py::test_binary_classification[xlm-xlm-mlm-17-1280] PASSED                      [ 12%]
tests/test_classification.py::test_binary_classification[roberta-roberta-base] PASSED                     [ 16%]
tests/test_classification.py::test_binary_classification[distilbert-distilbert-base-uncased] PASSED       [ 20%]
tests/test_classification.py::test_binary_classification[albert-albert-base-v1] PASSED                    [ 25%]
tests/test_classification.py::test_binary_classification[camembert-camembert-base] PASSED                 [ 29%]
tests/test_classification.py::test_binary_classification[xlmroberta-xlm-roberta-base] PASSED              [ 33%]
tests/test_classification.py::test_multiclass_classification[bert-bert-base-uncased] PASSED               [ 37%]
tests/test_classification.py::test_multiclass_classification[xlnet-xlnet-base-cased] PASSED               [ 41%]
tests/test_classification.py::test_multiclass_classification[xlm-xlm-mlm-17-1280] PASSED                  [ 45%]
tests/test_classification.py::test_multiclass_classification[roberta-roberta-base] PASSED                 [ 50%]
tests/test_classification.py::test_multiclass_classification[distilbert-distilbert-base-uncased] PASSED   [ 54%]
tests/test_classification.py::test_multiclass_classification[albert-albert-base-v1] PASSED                [ 58%]
tests/test_classification.py::test_multiclass_classification[camembert-camembert-base] PASSED             [ 62%]
tests/test_classification.py::test_multiclass_classification[xlmroberta-xlm-roberta-base] PASSED          [ 66%]
tests/test_classification.py::test_multilabel_classification[bert-bert-base-uncased] PASSED               [ 70%]
tests/test_classification.py::test_multilabel_classification[xlnet-xlnet-base-cased] PASSED               [ 75%]
tests/test_classification.py::test_multilabel_classification[xlm-xlm-mlm-17-1280] PASSED                  [ 79%]
tests/test_classification.py::test_multilabel_classification[roberta-roberta-base] PASSED                 [ 83%]
tests/test_classification.py::test_multilabel_classification[distilbert-distilbert-base-uncased] PASSED   [ 87%]
tests/test_classification.py::test_multilabel_classification[albert-albert-base-v1] PASSED                [ 91%]
tests/test_named_entity_recognition.py::test_named_entity_recognition PASSED                              [ 95%]
tests/test_question_answering.py::test_question_answering PASSED                                          [100%]

---------- coverage: platform linux, python 3.6.10-final-0 -----------
Name                                                                        Stmts   Miss  Cover
-----------------------------------------------------------------------------------------------
simpletransformers/classification/__init__.py                                   2      0   100%
simpletransformers/classification/classification_model.py                     412    139    66%
simpletransformers/classification/classification_utils.py                     119     65    45%
simpletransformers/classification/multi_label_classification_model.py          45      6    87%
simpletransformers/classification/transformer_models/__init__.py                0      0   100%
simpletransformers/classification/transformer_models/albert_model.py           27      2    93%
simpletransformers/classification/transformer_models/bert_model.py             27      2    93%
simpletransformers/classification/transformer_models/camembert_model.py         6      0   100%
simpletransformers/classification/transformer_models/distilbert_model.py       30      2    93%
simpletransformers/classification/transformer_models/roberta_model.py          27      2    93%
simpletransformers/classification/transformer_models/xlm_model.py              25      2    92%
simpletransformers/classification/transformer_models/xlm_roberta_model.py       6      0   100%
simpletransformers/classification/transformer_models/xlnet_model.py            27      2    93%
-----------------------------------------------------------------------------------------------
TOTAL                                                                         753    222    71%

================================== 24 passed, 58 warnings in 297.63s (0:04:57) ==================================

```

### CODE REVIEW

**Comment by kinoute** [comment]
Great work.

**Comment by marctorrellas** [comment]
> This is great, thank you! I've been meaning to add proper tests forever (not a good thing to procrastinate on, I know!).
> 
> While I understand the reasons for the line length limit, I really don't want to enforce it on all lines in the project. Sometimes, it makes the code far less readable (list comprehensions for example). I do realize that there are lines that could do with some breaking up, but I don't want to make the line length limit a hard rule. Do you mind adding an exception to the line length rule in the linter?

I understand your concern about the line length rule but if you use black you have that by default (with threshold=88). While it's a bit bad for lines e.g. 90 characters, I would say it's good 99% of cases and forces developers to write in a clean and standardised way

This PR is a really great addition @flaviussn , why don't you update the README?. Plus, I have two suggestions (but maybe can be done in another PR):
- using isort
- asking devs to add pre-commit hooks so we ensure people use black in any submission. I did it for hyperopt, see https://github.com/hyperopt/hyperopt/blob/master/README.md

**Comment by ThilinaRajapakse** [comment]
I have been planning to refactor the code as some parts are getting a little unwieldy. This includes breaking up complex statements and/or moving them to separate functions. However, I must still disagree with breaking up lines arbitrarily to keep them under the line length limit as this makes the code less readable. The black formatter can be configured to use a longer line length, right?

**Comment by marctorrellas** [comment]
yeah, there are very few things that can be touched, and this is one of them. I think 88 is quite long, what length do you suggest? (conventional python is 80) https://softwareengineering.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width

**Comment by ThilinaRajapakse** [comment]
I'm well aware of the PEP recommendation of 80 columns. I tend to agree with Raymond Hettinger that a 90-ish limit is more sensible. However, considering the type of this project, I'd go with 120.

**Comment by kinoute** [comment]
I use 120 personally. I always found 80 to be too small.

**Comment by ThilinaRajapakse** [comment]
I agree. In my opinion, using 80 in math-heavy programs is impractical. The Hugging Face Transformers also seems to be going with 120.

**Comment by flaviussn** [comment]
I used the default black length because I think that a "shorter" line length (80-90 characters) is better for side-by-side diff review on typical screen resolutions. 

If you want I can change it according to Hugging Face Transformers configuration.

**Comment by ThilinaRajapakse** [comment]
I understand. But I feel that it makes it a lot harder to understand the code.

Please do make the change.

**Comment by marctorrellas** [comment]
what do you guys think about my two proposals?

**Comment by flaviussn** [comment]
> what do you guys think about my two proposals?

I think it's a good idea. Let me pls first finish this PR

**Comment by ThilinaRajapakse** [comment]
@all-contributors please add @flaviussn  for code

**Comment by ThilinaRajapakse** [comment]
@all-contributors please add @flaviussn  for doc

**Pull request merged**
