### PR TITLE
add examples for different ways of saving model checkpoints

### PR DESCRIPTION
**Pull request by pablonm3**
After struggling with understanding how to use the save checkpoint functionality(see the issue I opened: https://github.com/ThilinaRajapakse/simpletransformers/issues/862) I decided to add some examples to the docs to assist others as well as my future self.

### CODE REVIEW

**Review by ThilinaRajapakse — CHANGES_REQUESTED** [review]
Looks good. But, shall we move this to the [tips and tricks](https://simpletransformers.ai/docs/tips-and-tricks/) page instead? I cleaned up the `usage` page as it was getting cluttered (and removed duplicate information)

**Comment by pablonm3** [comment]
> Looks good. But, shall we move this to the [tips and tricks](https://simpletransformers.ai/docs/tips-and-tricks/) page instead? I cleaned up the `usage` page as it was getting cluttered (and removed duplicate information)

@ThilinaRajapakse done

**Comment by zacc** [comment]
Hi, you have misspelt epoch as ephoc throughout this PR. It should be consistent with the model args spelling and transformers!

(PS was looking to learn how to do this myself so thanks for submitting this PR!)

**Comment by pablonm3** [comment]
> Hi, you have misspelt epoch as ephoc throughout this PR. It should be consistent with the model args spelling and transformers!
> 
> (PS was looking to learn how to do this myself so thanks for submitting this PR!)

thank you!, I fixed the typo ;)

**Review by ThilinaRajapakse — APPROVED** [review]
Great! Looks good.

**Pull request merged**
