### PR TITLE
Adding prefix space for Roberta and similar tokenizers

### LINKED ISSUE #458: RoBERTa tokenization does not add leading space
The GPT-2 style BPE encoding used by RoBERTa requires that all words begin with a space (see [here](https://github.com/huggingface/transformers/issues/1196) and [here](https://github.com/pytorch/fairseq/blob/master/fairseq/models/roberta/hub_interface.py#L38-L56). For this reason the encode_plus method for Huggingface RobertaTokenizer automatically adds a leading space, so that a sentence like "It's raining" become " It's raining" before adding beginning and end of string tokens. 

However, the tokenization method used by by simpletransformers (calling `.tokenize()`, manually adding special tokens, and calling `.convert_tokens_to_ids()`) does not add this space. In my investigation I saw that prediction results from a trained model may differ between the two methods. Tokenization here should probably conform to that suggested by fairseq, adding the leading space.

### PR DESCRIPTION
**Pull request by ThilinaRajapakse**
fixes #458

### CODE REVIEW

**Comment by ThilinaRajapakse** [comment]
Do you mind checking this out, please? @guy-mor

It should fix both #457 and #458

**Comment by guy-mor** [comment]
Seems good. A small difference between the HF tokenizer and this implementation is that the former only adds a prefix space if the sentence doesn't begin with a space whereas here it is added anyway, but this shouldn't really matter in practice.

I suggest noting in the changelog that this may slightly change the predictions of models trained before this change.

**Comment by ThilinaRajapakse** [comment]
I think it was mentioned in the issue thread that multiple spaces wouldn't matter but I'm not too sure about it. But, since it's trivial to check whether the sentence begins with space so I'll follow the same logic.

**Comment by ThilinaRajapakse** [comment]
@all-contributors add @guy-mor for bug

**Pull request merged**
