### PR TITLE
Implements Lazy Loading for QA tasks

### PR DESCRIPTION
**Pull request by ThilinaRajapakse**
This PR implements Lazy Loading support for training QA models.

Special requirements:
- Requires `train_data` to be a `str` pointing to a [JSONL](http://jsonlines.org/) file.
- Lazy loading is only supported for training and not for evaluation.

Testing:
- A minimal testing script can be found at `examples/question_answering/lazy_qa.py`

To do:
- Update docs

### CODE REVIEW

**Comment by ThilinaRajapakse** [comment]
@flozi00

**Comment by flozi00** [comment]
Is it an already working example ?

**Comment by ThilinaRajapakse** [comment]
Yeah. The example can be run directly.

**Comment by flozi00** [comment]
It seems to work good, but sometimes an error occurres while training, caused by an broken dataset.
That's the danger of lazy loading, that you don't see if your dataset is good.
Can we implement an check for that while loading it ?

**Comment by ThilinaRajapakse** [comment]
I don't see how that is possible as the dataset doesn't get loaded into memory in the first place.

**Pull request merged**
