### PR TITLE
Add examples subdirectory with minimal working examples for discovery

### PR DESCRIPTION
**Pull request by GillesJ**
I have added a subdirectory at project root `examples/` containing the minimal working examples for text classification.

This should help with discovery of this project as it enables quick testing of code after setup.

### CODE REVIEW

**Comment by GillesJ** [comment]
I will merge the README and add the other examples as well as soon as I have time. Seems like there is no need to further nest the example scripts in subdirectories as there are about 8 example scripts. I will rename files to reflect the task better though.

**Comment by ThilinaRajapakse** [comment]
True. But I think it might be helpful long-term if and when more functionality is added. It also reflects the structure of the project as the classes are split by task.

**Comment by GillesJ** [comment]
So I merged the README to latest version and added a line on where to find the minimal example scripts.

I added subdirectories by task as discussed. You can add real-world dataset examples this way more easily.

**Comment by ThilinaRajapakse** [comment]
@all-contributors please add for @GillesJ code

**Comment by ThilinaRajapakse** [comment]
@all-contributors please add @GillesJ for doc

**Pull request merged**
