### PR TITLE
Add herbert

### PR DESCRIPTION
**Pull request by Zhylkaaa**
Adds Hebert model - SOTA for polish language

### CODE REVIEW

**Comment by Zhylkaaa** [comment]
sometimes this tensor board error gets pretty annoying, for example when you want to log a dict to wandb, tensor board want lat you0

**Review by ThilinaRajapakse — APPROVED** [review]
Thanks, I'll merge this! Would you mind adding `Herbert` to the supported models for classification and NER in the docs as well?

**Comment by Zhylkaaa** [comment]
I am not entirely sure this is the right way to add this to docs, but I've tried :)

**Comment by ThilinaRajapakse** [comment]
Yes, this is the way!

**Pull request merged**
