### PR TITLE
Support for distributed training (Language modeling)

### PR DESCRIPTION
**Pull request by ThilinaRajapakse**
This PR aims to solve #440

### CODE REVIEW

**Comment by ThilinaRajapakse** [comment]
Thank you, @cahya-wirawan! I opened a pull request for easy comparison.

I forgot that I didn't add `DistributedDataset` and `DistributedSampler` when the library was originally created.

Does this successfully implement distributed training? I'll test it out soon.

The Trainer class was added to Transformers very recently. Simple Transformers had features like wandb integration, evaluation during training, and early stopping before Transformers did which necessitated the custom (admittedly rather complicated) training loops. Also, the reason to have different data processing classes/functions is because Transformers didn't use multiprocessing at the time (not sure if they do now). Tokenization and feature conversion in Simple Transformers was many times faster since we used multiprocessing from the start. 

I do have tentative plans to make it more consistent between the different tasks and possibly move it to a separate class. I won't be pulling the Trainer class from Transformers directly though.

**Comment by cahya-wirawan** [comment]
Hi,
The distributed training is working as expected, I made some tests using 4 GPUs, and the training was distributed nicely in to 4 GPUs. Of course it would be good if other user can test it to make sure that it really works. There are also few things I still don't include at the moment such as DistributedSampler for evaluation and testing.

I didn't make a PR because my branch was just meant to be my development branch, not a nice and clean branch worth for PR :-) For example I added by accident the script run_lm_train.py in to the main directory. I also use TextDataset and LineByLineDataset from the Transformers since it is necessary due to the error message in #440 (... json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)).

**Comment by ThilinaRajapakse** [comment]
Sorry about the premature PR! I made it so that it would be easier for me to test it. :sweat_smile: 
Please feel free to open your own PR when you are ready and I'll close this one.

I only have 2 GPUs on my system and the training is distributed to both with the provided command. 

I agree with going with those two datasets from Transformers as we now have the separate SimpleDataset. The user can choose which one to use according to the situation.

**Comment by cahya-wirawan** [comment]
It's no problem, we can still use this PR. If there is any unnecessary file, we can remove it later and update the code.
Btw, I am also far away from an experience developer on distributed training. I started to try it last week when I was disappointed with DataParalell which also promise to run a model in multiple GPU. 
It is very easy to use DataParallel, but the main disadvantage is that we get imbalanced usage of GPU. The main GPU will be loaded the most, so we can't use the most of all GPUs. DataParallel is also a multi-threading process where python has bad performance due to Global Interpreter Lock (GIL)

**Comment by ThilinaRajapakse** [comment]
Sounds good. Shall we move the `run_lm_training` example to the `examples/` directory? Once that is done, I think we can merge this.

Yes, the distributed training approach does seem superior. It managed to run without any issues despite my 2 GPUs being different from each other.

**Comment by cahya-wirawan** [comment]
How about just to add the necessary lines for distributed training to examples/language_generation/train_new_lm.py, so we have only a script to train in a single and multiple gpu? just like run_lm_training.py where we can use it for both single and multiple gpus.

**Comment by ThilinaRajapakse** [comment]
Yeah, that's better. Come to think of it, `language_generation` directory should probably be renamed to `language_modeling`.

**Comment by ThilinaRajapakse** [comment]
Nice. This is ready to merge now, right?

**Comment by cahya-wirawan** [comment]
> Nice. This is ready to merge now, right?

yes you can merge it now. I can add DistributedSampler for evaluation and testing later

**Comment by ThilinaRajapakse** [comment]
Awesome!

**Comment by ThilinaRajapakse** [comment]
@all-contributors add @cahya-wirawan for code

**Pull request merged**
